<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1QM04gH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1QM04gH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1QM04gH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1QM04gH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1QM04gH\App_KernelDevDebugContainer([
    'container.build_hash' => '1QM04gH',
    'container.build_id' => 'dfab3c2e',
    'container.build_time' => 1708510192,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container1QM04gH');
